### ISSUE TITLE
Pre-installed accounts aren't available

### ISSUE THREAD

**Issue by markvdlaan93** [XetaIO/Xeta#216]
I just installed this project and ran the database migrations with the command bin/cake migrations migrate. However, the pre-installed accounts aren't loaded. [In this link](https://devhub.io/repos/Xety-Xeta) you suggest to load config/Schema/xeta.sql. Is there something missing in the migrations?

**Comment by Xety** [comment]
Use the installation instructions on the [GitHub Readme](https://github.com/XetaIO/Xeta/blob/master/README.md) :
```
composer create-project --prefer-dist xety/xeta <application_name>
composer run-script installation
```
