### ISSUE TITLE
Unable to write the cookie for tracking

### ISSUE THREAD

**Issue by markvdlaan93** [XetaIO/Xeta#219]
When I click on the 'I understood'-button (agreeing with using cookie tracker), it suggests that the cookie can't be written (tried on Safari, Firefox and Chrome on both CakePHP 3.3.16 and 3.4.5). Everything works accordingly except this aspect. I tried to track down what went wrong but I can't seem to figure it out. Is this a bug?

**Comment by Xety** [comment]
Hello, thanks for the feedback, i was able to reproduce it. I will fix it ASAP.

**Comment by Xety** [comment]
Closed as #222 is open now.
